config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root to 'tasks#index'

  # user can list the tasks
  get 'tasks', to: 'tasks#index'

  # user can add a new task
  get 'tasks/new', to: 'tasks#new'
  post 'tasks', to: 'tasks#create'

 # user can view the details of the task
  get 'tasks/:id', to: 'tasks#show', as: :task

  # user can edit a task
  get 'tasks/:id/edit', to: 'tasks#edit', as: :task_edit
  patch 'tasks/:id', to: 'tasks#update'

  # user can remove a task
  delete 'tasks/:id', to: 'tasks#destroy', as: :task_delete
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task) #, notice: 'Your task was saved!'
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to task_path(@task) #, notice: 'Your task was successfully updated!'
  end

  def destroy
    @task.destroy
    redirect_to tasks_path #, notice: 'Your task was destroyed'
  end

  private

  def task_params
    params.require(:task).permit(:name, :details, :completed)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/edit.html.erb
<h2>Edit this task</h2>

<div class="container">
<%= form_for @task do |f| %>
  <div>
    <%= f.label :name, "Enter the title for your task" %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :details, "What is this task about?" %>
    <%= f.text_field :details %>
  </div>

  <%= f.submit %>
<% end %>
</div>

app/views/tasks/index.html.erb
<h1>Your Task Manager</h1>

<h3>Welcome! Here are your tasks</h3>
<p>Click on a task to see more</p>

<ul>
  <% @tasks.each do |mytask| %>
    <li>
      <%= link_to task_path(mytask.id) do %>
      <%= mytask.name %>
      <%= link_to ' - 🗑', task_delete_path(mytask), method: :delete %>
      <% end %>
    </li>
  <% end %>
</ul>

<div class="button">
  <h4><%= link_to '➕ Add a task', tasks_new_path, method: :get %></h4>
</div>

app/views/tasks/new.html.erb
<h2>Create a new task</h2>

<div class="container">
<%= form_for (@task) do |f| %>
  <div>
    <%= f.label :name, "Enter the title for your task" %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :details, "What is this task about?" %>
    <%= f.text_field :details %>
  </div>

  <%= f.submit 'Do it!' %>
<% end %>
</div>

app/views/tasks/show.html.erb
<h2>To Do</h2>

<h4><%= @task.name %></h4>
<span><%= @task.details %></span>
<p>Completed? ➡️ <%= @task.completed %></p>

<div class="button">
  <h4><%= link_to '📝 Edit a task', task_edit_path(@task.id), method: :get %>
    <%= flash[:notice] %>
  </h4>
</div>

<div class="button">
  <h4><%= link_to 'Back to tasks list' , tasks_path, method: :get %></h4>
</div>

<!-- <div class="button">
  <h4><%#= link_to '➖ Delete a task', task_path(@tasks.id), method: :delete %></h4>
</div> -->